# Generated by Django 4.2.11 on 2024-12-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Ingredients', models.TextField()),
                ('Iamge', models.ImageField(upload_to='')),
            ],
        ),
    ]
