# Generated by Django 4.2.11 on 2024-12-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='Iamge',
            field=models.ImageField(upload_to='image'),
        ),
    ]
